export const strings = {
  hi: {
    greeting: 'नमस्ते!',
    tagline: 'दवाई खोजें',
    searchPlaceholder: 'दवाई का नाम लिखें...',
    voiceBtn: 'बोलकर खोजें',
    voiceListening: 'सुन रहा हूँ...',
    scanBtn: 'Scan करें',
    callBtn: 'Call करें',
    inStock: 'उपलब्ध',
    outOfStock: 'उपलब्ध नहीं',
    noResults: 'कोई दवाई नहीं मिली',
    noResultsHint: 'दूसरे नाम से खोजें या दुकान पर Call करें',
    voiceUnsupported: 'आपके फ़ोन में Voice Search काम नहीं करता',
  },
  en: {
    greeting: 'Hello!',
    tagline: 'Find Your Medicine',
    searchPlaceholder: 'Search medicine name...',
    voiceBtn: 'Voice Search',
    voiceListening: 'Listening...',
    scanBtn: 'Scan',
    callBtn: 'Call',
    inStock: 'In Stock',
    outOfStock: 'Out of Stock',
    noResults: 'No medicines found',
    noResultsHint: 'Try a different name or call the store',
    voiceUnsupported: 'Voice search not supported on this browser',
  },
}
